[platformio]
default_envs = edboard_codex_probe
src_dir = src
boards_dir = ../boards

[env:edboard_codex_probe]
platform = platformio/espressif32 @ 6.13.0
platform_packages =
    platformio/framework-espidf @ 3.50503.0
    platformio/tool-esptoolpy @ 2.41100.0
framework = espidf
extra_scripts = pre:prepare_sdkconfig.py
board = edboard_n16r8
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0
